FROM node:alpine3.17
WORKDIR /app
COPY ./package.json ./

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "dev" ]; \
        then npm install; \
        else npm install --only=prod; \
        fi
        
COPY ./ ./
EXPOSE $PORT
CMD ["node", "index.js"]