version: "3"
services:
  e-learning:
    build:
      context: .
      args:
        NODE_ENV: dev
    ports:
      - "4043:4043"
    environment:
      - NODE_ENV=dev
      - PORT=4043
    depends_on:
      - redis
    command: ["npm", "run", "dev"]

  redis:
    image: redis
